skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'

environment:
  VS_VERSION: vs2017

platform:
  - x64

image: Visual Studio 2017

configuration:
  - Release

install:
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:
  - dep\bin-win\premake5.exe vs2017
  - msbuild build\vs\otfcc.sln /m:%NUMBER_OF_PROCESSORS% /nr:false /nologo /verbosity:minimal /property:Configuration=Release
  - make -f quick.make test

artifacts:
  - path: bin\release-x64\otfccbuild.exe
    name: otfccbuild

  - path: bin\release-x64\otfccdump.exe
    name: otfccdump

  - path: bin\release-x64\otfccdll.dll
    name: otfccdll
